name: Deploy tlisto

on:
  push:
    branches:
      - test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies 📦
        run: npm ci

      - name: Build 🏗️
        run: VITE_BASE_PATH=/tlisto/ npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: FTP Deploy 🚀
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_TEST_USERNAME }}
          password: ${{ secrets.FTP_TEST_PASSWORD }}

          local-dir: ./dist/
          server-dir: ./

          protocol: ftps
          dangerous-clean-slate: true
